spring:
    application:
        name: santander-dev-week
    
    datasource:
        url: jdbc:h2:mem:sdw2023
        username: sdw2023
        password: 
    
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
        open-in-view: false
        properties:
            hibernate:
                format_sql: true

    h2:
        console:
            enabled: true
            path: /h2-console
            settings:
                trace: false
                web-allow-others: false
